server.port=8091
spring.application.name=api-gateway
# Routing
spring.cloud.gateway.routes[0].id=order
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
