server.port=8222
spring.application.name=API-GATEWAY

spring.cloud.gateway.routes[0].id=order
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**
