server.port=8081
spring.application.name=ORDER-SERVICE

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/saga_design_pattern
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092
