server.port=8888
spring.application.name=PAYMENT-SERVICE
# Kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092
# Consumer
spring.cloud.stream.bindings.inventorySuccess-in-0.destination=inventory-success
# Producers
spring.cloud.stream.bindings.payment-success-out-0.destination=payment-success
spring.cloud.stream.bindings.payment-failed-out-0.destination=payment-failed
# Function
spring.cloud.function.definition=inventorySuccess
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
